<?php

namespace AppBundle\Entity\Election;

/**
 * CandidatureCallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatureCallRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOpenedAtDate(\DateTime $date = null)
    {
        if (!isset($date)) {
            $date = new \DateTime('now');
        }
        return $this->createQueryBuilder('c')
                ->where('c.openingDate < :date')
                ->andWhere('c.closingDate > :date')
                ->setParameter(':date', $date)
            ->getQuery()
            ->getResult();
    }
}
