<?php

namespace AppBundle\Entity\Election;

use AppBundle\Entity\Adherent;
use AppBundle\Entity\AdherentResponsability;
use AppBundle\Entity\Organ\OrganParticipation;
use Doctrine\ORM\EntityRepository;

/**
 * ElectionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElectionRepository extends EntityRepository
{
    public function findElectionResponsable(AdherentResponsability $adherentResponsability, OrganParticipation $organParticipation)
    {

        $electionResponsable = $this->createQueryBuilder('a')
            ->select('a')
            ->leftJoin('o.organ_participation', 'ao')
            ->where('ao.adherent_responsability = :adherent_responsability')
            ->setParameter('adherent', $adherentResponsability->getId())
            ->getQuery();


        return $electionResponsable->getResult();
    }
}