services:
    sonata.admin.adherent:
        class: AppBundle\Admin\AdherentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Fichier", label: "Adhérents"}
        arguments:
            - ~
            - AppBundle\Entity\Adherent
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.responsability:
        class: AppBundle\Admin\ResponsabilityAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Fichier", label: "Responsabilités"}
        arguments:
            - ~
            - AppBundle\Entity\Responsability
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.user:
        class: AppBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Application", label: "Utilisateurs du site"}
        arguments:
            - ~
            - AppBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.acces:
        class: AppBundle\Admin\AccessAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Application", label: "Gestion des accès"}
        arguments:
            - ~
            - AppBundle\Entity\Access
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
            - [ setRouter, [@router] ]
    sonata.admin.congres.thematic_contribution:
        class: AppBundle\Admin\Congres\ThematicContributionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Congrès 2015", label: "Contributions thématiques"}
        arguments:
            - ~
            - AppBundle\Entity\Congres\ThematicContribution
            - sonata.admin.congres.contribution_controller
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.congres.general_contribution:
        class: AppBundle\Admin\Congres\GeneralContributionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Congrès 2015", label: "Contributions générales"}
        arguments:
            - ~
            - AppBundle\Entity\Congres\GeneralContribution
            - sonata.admin.congres.contribution_controller
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.congres.contribution_controller:
        class: AppBundle\Admin\Congres\Controller\ContributionAdminController
        calls:
            - [ setContainer, [@service_container] ]

    sonata.admin.event:
        class: AppBundle\Admin\EventAdmin
        arguments: [~, AppBundle\Entity\Event\Event, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Evenements", label: "Évenements"}

    sonata.admin.event_adherent_registration:
        class: AppBundle\Admin\EventAdherentRegistrationAdmin
        arguments: [~, AppBundle\Entity\Event\EventAdherentRegistration, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Evenements", label: "Inscription des adherents"}

    sonata.admin.address:
        class: AppBundle\Admin\AddressAdmin
        arguments: [~, AppBundle\Entity\Address, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Address, show_in_dashboard: false }

    sonata.admin.text_group:
        class: AppBundle\Admin\TextGroupAdmin
        arguments: [~, AppBundle\Entity\Text\TextGroup, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Texte", label: "Groupes de textes"}

    sonata.admin.text:
        class: AppBundle\Admin\TextAdmin
        arguments: [~, AppBundle\Entity\Text\Text, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Texte", label: "Textes"}

    app.admin.amendment:
        class: AppBundle\Admin\AmendmentAdmin
        arguments: [~, AppBundle\Entity\Text\Amendment, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Texte", label: "Amendements"}

    sonata.admin.individual_organ_text_vote:
        class: AppBundle\Admin\IndividualOrganTextVoteAdmin
        arguments: [~, AppBundle\Entity\Vote\IndividualOrganTextVote, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Texte", label: "Procès Verbaux"}

    sonata.admin.vote_rule:
        class: AppBundle\Admin\VoteRuleAdmin
        arguments: [~, AppBundle\Entity\Vote\VoteRule, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Texte", label: "Règles de votes" }
        calls:
            - [setSubClasses, [{threshold: AppBundle\Entity\Vote\ThresholdVoteRule}]]

    sonata.admin.election:
        class: AppBundle\Admin\ElectionAdmin
        arguments: [~, AppBundle\Entity\Election\Election, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Election", label: "Elections" }

    sonata.admin.election_group:
        class: AppBundle\Admin\ElectionGroupAdmin
        arguments : [~, AppBundle\Entity\Election\ElectionGroup, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Election", label: "Type d'élection"}

    sonata.admin.result:
        class: AppBundle\Admin\ResultAdmin
        arguments : [~, AppBundle\Entity\Election\Result, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Election", label: "Résultats"}

    sonata.admin.event_meal:
        class: AppBundle\Admin\EventMealAdmin
        arguments: [~, AppBundle\Entity\Event\EventMeal, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: EventMeal, show_in_dashboard: false }

    sonata.admin.event_cost:
        class: AppBundle\Admin\EventCostAdmin
        arguments: [~, AppBundle\Entity\Event\EventCost, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: EventCost, show_in_dashboard: false }

    sonata.admin.event_role:
        class: AppBundle\Admin\EventRoleAdmin
        arguments: [~, AppBundle\Entity\Event\EventRole, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Evenements", label: "Rôles d'évenements", show_in_dashboard: false }

    sonata.admin.adherent_responsability:
        class: AppBundle\Admin\AdherentResponsabilityAdmin
        arguments: [~, AppBundle\Entity\AdherentResponsability, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: AdherentResponsability, show_in_dashboard: false}

    sonata.admin.payment:
        class: AppBundle\Admin\PaymentAdmin
        arguments: [~, AppBundle\Entity\Payment\Payment, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Payment, show_in_dashboard: false}
        calls:
            - [setSubClasses, [{membership: AppBundle\Entity\Payment\MembershipPayment, event: AppBundle\Entity\Payment\EventPayment}]]

    sonata.admin.payment.event_payment:
        class: AppBundle\Admin\EventPaymentAdmin
        arguments: [~, AppBundle\Entity\Payment\EventPayment, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: EventPayment, show_in_dashboard: false}

    app.admin.organ_vote_rule:
        class: AppBundle\Admin\OrganVoteRuleAdmin
        arguments: [~, AppBundle\Entity\Vote\OrganVoteRule, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: OrganVoteRule, show_in_dashboard: false}

    app.admin.organ:
        class: AppBundle\Admin\OrganAdmin
        arguments: [~, AppBundle\Entity\Organ\Organ, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Organ, label: Organ}

    app.admin.individual_organ_text_vote_agregation:
        class: AppBundle\Admin\IndividualOrganTextVoteAgregationAdmin
        arguments: [~, AppBundle\Entity\Vote\IndividualOrganTextVoteAgregation, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: IndividualOrganTextVoteAgregation, show_in_dashboard: false}

    sonata.admin.sleeping:
        class: AppBundle\Admin\SleepingSiteAdmin
        arguments: [~, AppBundle\Entity\Event\SleepingSite, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Evenements", label: "Lieu de couchage"}

    sonata.admin.roomtype:
        class: AppBundle\Admin\RoomTypeAdmin
        arguments: [~, AppBundle\Entity\Event\RoomType, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Evenements", label: "Type de chambre", }

    sonata.admin.bedroom:
            class: AppBundle\Admin\BedroomAdmin
            arguments: [~, AppBundle\Entity\Event\Bedroom, SonataAdminBundle:CRUD]
            tags:
                - {name: sonata.admin, manager_type: orm, group: "Evenements", label: "Chambres"}

    sonata.admin.booking:
        class: AppBundle\Admin\BookingAdmin
        arguments: [~, AppBundle\Entity\Event\Booking, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Evenements", label: "Réservations"}