security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        # for root and test users
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:

        # Sonata roles
        ROLE_SONATA_ADMIN_EVENT_REGISTRATION_VIEWER:
            - ROLE_SONATA_ADMIN_EVENT_ADHERENT_REGISTRATION_VIEW
            - ROLE_SONATA_ADMIN_EVENT_ADHERENT_REGISTRATION_LIST
        ROLE_SONATA_ADMIN_EVENT_REGISTRATION_EDITOR:
            - ROLE_SONATA_ADMIN_EVENT_ADHERENT_REGISTRATION_CREATE
            - ROLE_SONATA_ADMIN_EVENT_ADHERENT_REGISTRATION_EDIT
        ROLE_SONATA_ADMIN_EVENT_REGISTRATION_ADMIN:
            - ROLE_SONATA_ADMIN_EVENT_ADHERENT_REGISTRATION_DELETE
            - ROLE_SONATA_ADMIN_EVENT_ADHERENT_REGISTRATION_EXPORT

        ROLE_SONATA_ADMIN_EVENT_VIEWER:
            - ROLE_SONATA_ADMIN_EVENT_VIEW
            - ROLE_SONATA_ADMIN_EVENT_LIST
        ROLE_SONATA_ADMIN_EVENT_EDITOR:
            - ROLE_SONATA_ADMIN_EVENT_CREATE
            - ROLE_SONATA_ADMIN_EVENT_EDIT
        ROLE_SONATA_ADMIN_EVENT_ADMIN:
            - ROLE_SONATA_ADMIN_EVENT_DELETE
            - ROLE_SONATA_ADMIN_EVENT_EXPORT

        ROLE_SONATA_ADMIN_INDIVIDUAL_ORGAN_TEXT_VOTE_VIEWER:
            - ROLE_SONATA_ADMIN_INDIVIDUAL_ORGAN_TEXT_VOTE_VIEW
            - ROLE_SONATA_ADMIN_INDIVIDUAL_ORGAN_TEXT_VOTE_LIST
            - ROLE_SONATA_ADMIN_INDIVIDUAL_ORGAN_TEXT_VOTE_EXPORT
        ROLE_SONATA_ADMIN_INDIVIDUAL_ORGAN_TEXT_VOTE_EDITOR:
            - ROLE_SONATA_ADMIN_INDIVIDUAL_ORGAN_TEXT_VOTE_CREATE
            - ROLE_SONATA_ADMIN_INDIVIDUAL_ORGAN_TEXT_VOTE_EDIT
        ROLE_SONATA_ADMIN_INDIVIDUAL_ORGAN_TEXT_VOTE_ADMIN:
            - ROLE_SONATA_ADMIN_INDIVIDUAL_ORGAN_TEXT_VOTE_DELETE

        ROLE_SONATA_ADMIN_INDIVIDUAL_ORGAN_TEXT_VOTE_AGREGATION_VIEWER:
            - ROLE_SONATA_ADMIN_INDIVIDUAL_ORGAN_TEXT_VOTE_AGREGATION_VIEW
            - ROLE_SONATA_ADMIN_INDIVIDUAL_ORGAN_TEXT_VOTE_AGREGATION_LIST
            - ROLE_SONATA_ADMIN_INDIVIDUAL_ORGAN_TEXT_VOTE_AGREGATION_EXPORT
        ROLE_SONATA_ADMIN_INDIVIDUAL_ORGAN_TEXT_VOTE_AGREGATION_EDITOR:
            - ROLE_SONATA_ADMIN_INDIVIDUAL_ORGAN_TEXT_VOTE_AGREGATION_CREATE
            - ROLE_SONATA_ADMIN_INDIVIDUAL_ORGAN_TEXT_VOTE_AGREGATION_EDIT
        ROLE_SONATA_ADMIN_INDIVIDUAL_ORGAN_TEXT_VOTE_AGREGATION_ADMIN:
            - ROLE_SONATA_ADMIN_INDIVIDUAL_ORGAN_TEXT_VOTE_AGREGATION_DELETE

        # Role in use
        ROLE_ADMIN_PANEL:
            - ROLE_USER

        ROLE_VOTE_COMITY:
            - ROLE_ADMIN_PANEL
            - ROLE_SONATA_ADMIN_INDIVIDUAL_ORGAN_TEXT_VOTE_VIEWER
            - ROLE_SONATA_ADMIN_INDIVIDUAL_ORGAN_TEXT_VOTE_AGREGATION_VIEWER

        ROLE_STAFF:
            - ROLE_ADMIN_PANEL
            - ROLE_SONATA_ADMIN_EVENT_REGISTRATION_VIEWER
            - ROLE_SONATA_ADMIN_EVENT_REGISTRATION_EDITOR

        ROLE_ORGANIZER:
            - ROLE_STAFF
            - ROLE_SONATA_ADMIN_EVENT_REGISTRATION_ADMIN
            - ROLE_SONATA_ADMIN_EVENT_VIEWER
            - ROLE_SONATA_ADMIN_EVENT_EDITOR
        ROLE_ADMIN:
            - ROLE_ORGANIZER
            - ROLE_SONATA_ADMIN
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory_root:
            memory:
                users:
                    root: { password: %superadmin_password%, roles: 'ROLE_SUPER_ADMIN' }
        chained_fos_userbundle:
            chain:
                providers: [in_memory_root, fos_userbundle]
        testing:
             memory:
                users:
                    user:  { password: user, roles: 'ROLE_USER' }
                    admin: { password: admin, roles: 'ROLE_ADMIN' }

    access_decision_manager:
        strategy: unanimous


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: chained_fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

        default:
            anonymous: ~

    access_control:
        - { path: ^/payment-ipn/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mot-de-passe, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN_PANEL }
        - { path: ^/event, role: ROLE_USER }
        - { path: ^/adherents/register, role: ROLE_USER }
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
