security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        # for root and test users
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory_root:
            memory:
                users:
                    root: { password: %superadmin_password%, roles: 'ROLE_SUPER_ADMIN' }
        chained_fos_userbundle:
            chain:
                providers: [in_memory_root, fos_userbundle]
        testing:
             memory:
                users:
                    user:  { password: user, roles: 'ROLE_USER' }
                    admin: { password: admin, roles: 'ROLE_ADMIN' }


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: chained_fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

        default:
            anonymous: ~

    access_control:
        - { path: ^/payment-ipn/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mot-de-passe, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }
