# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.user.registration.form.type:
        class: AppBundle\Form\Type\RegistrationType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: app_user_registration }
    app.user.registration.registration_listener:
        class: AppBundle\EventListener\RegistrationListener
        arguments:
            - @router
            - @templating
            - @mailer
            - @doctrine.orm.entity_manager
            - @fos_user.user_manager
            - @fos_user.registration.form.factory
        tags:
            - { name: kernel.event_subscriber }
    app.user.profile.form.type:
        class: AppBundle\Form\Type\ProfileType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: app_user_profile }
    app.congres.contribution_voter:
        class:      AppBundle\Security\Congres\ContributionVoter
        public:     false
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
           - { name: security.voter }

    app.congres.text_group_voter:
        class:      AppBundle\Security\Text\TextGroupVoter
        public:     false
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
           - { name: security.voter }

    app.congres.text_voter:
        class:      AppBundle\Security\Text\TextVoter
        public:     false
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
           - { name: security.voter }

    app.calendar_voter:
        class:      AppBundle\Security\CalendarVoter
        public:     false
        arguments: [@doctrine.orm.entity_manager]
        tags:
           - { name: security.voter }
    app.payment_response_listener:
        class: AppBundle\EventListener\PaymentResponseListener
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_listener, event: paybox.ipn_response, method: onPaymentIpnResponse }

# Import admin services
imports:
    - { resource: @AppBundle/Resources/config/admin.yml }
