# Import admin services
imports:
    - { resource: admin.yml }

services:
    fos_user.doctrine_registry:
        alias: doctrine

    app.user.registration.form.type:
        class: AppBundle\Form\Type\RegistrationType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: app_user_registration }
    app.user.registration.registration_listener:
        class: AppBundle\EventListener\RegistrationListener
        arguments:
            - @router
            - @templating
            - @mailer
            - @doctrine.orm.entity_manager
            - @fos_user.user_manager
            - @fos_user.registration.form.factory
        tags:
            - { name: kernel.event_subscriber }
    app.user.profile.form.type:
        class: AppBundle\Form\Type\ProfileType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: app_user_profile }

    app.congres.contribution_voter:
        class:      AppBundle\Security\Congres\ContributionVoter
        public:     false
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
           - { name: security.voter }

    app.congres.text_group_voter:
        class:      AppBundle\Security\Text\TextGroupVoter
        public:     false
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
           - { name: security.voter }

    app.congres.text_voter:
        class:      AppBundle\Security\Text\TextVoter
        public:     false
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
           - { name: security.voter }

    app.congres.amendment_process_voter:
        class:      AppBundle\Security\AmendmentProcessVoter
        public:     false
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
           - { name: security.voter }

    app.calendar_voter:
        class:      AppBundle\Security\CalendarVoter
        public:     false
        arguments: [@doctrine.orm.entity_manager]
        tags:
           - { name: security.voter }

    app.election_report_voter:
        class:      AppBundle\Security\ElectionReportVoter
        public:     false
        tags:
           - { name: security.voter }

    app.payment_response_listener:
        class: AppBundle\EventListener\PaymentResponseListener
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_listener, event: paybox.ipn_response, method: onPaymentIpnResponse }

    app.event_booking_voter:
        class:      AppBundle\Security\Congres\BookingVoter
        arguments: [@doctrine.orm.entity_manager]
        public:     false
        tags:
           - { name: security.voter }

    app.congres.event_register_voter:
        class:      AppBundle\Security\EventRegisterVoter
        public:     false
        tags:
           - { name: security.voter }

    app.election.departmental_voter:
        class:      AppBundle\Security\DepartmentalElectionVoter
        arguments: [@doctrine.orm.entity_manager, %cosecretaire_departement_id% ]
        public:     false
        tags:
          - { name : security.voter }

    app.booking_listener:
        class: AppBundle\EventListener\BookingListener
        arguments: [@mailer]
        tags:
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postPersist }

    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments : ['@knp_menu.factory', '@doctrine.orm.entity_manager']

    app.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: app.menu_builder
        factory_method: createMainMenu
        arguments: ['@request']
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main}
