<?php

namespace AppBundle\Entity\Text;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Text\Text;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmendmentItemRepository extends EntityRepository
{
    protected $classname = 'AppBundle\Entity\Text\AmendmentItem';

    public function getCountByText(Text $text)
    {
        return $this->getEntityManager()->createQueryBuilder('ai')
            ->select('count(item.id)')
            ->from('AppBundle:Text\AmendmentItem', 'item')
            ->where('item.text = :text')
            ->setParameter(':text', $text->getId())
            ->getQuery()->getSingleScalarResult();
    }
}
