services:
    sonata.admin.adherent:
        class: AppBundle\Admin\AdherentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Fichier", label: "Adhérents"}
        arguments:
            - ~
            - AppBundle\Entity\Adherent
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.instance:
        class: AppBundle\Admin\InstanceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Fichier", label: "Instances"}
        arguments:
            - ~
            - AppBundle\Entity\Instance
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.user:
        class: AppBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Application", label: "Utilisateurs"}
        arguments:
            - ~
            - AppBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.acces:
        class: AppBundle\Admin\AccessAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Application", label: "Gestion des accès"}
        arguments:
            - ~
            - AppBundle\Entity\Access
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
            - [ setRouter, [@router] ]
    sonata.admin.congres.thematic_contribution:
        class: AppBundle\Admin\Congres\ThematicContributionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Congrès 2015", label: "Contributions thématiques"}
        arguments:
            - ~
            - AppBundle\Entity\Congres\ThematicContribution
            - sonata.admin.congres.contribution_controller
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.congres.general_contribution:
        class: AppBundle\Admin\Congres\GeneralContributionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Congrès 2015", label: "Contributions générales"}
        arguments:
            - ~
            - AppBundle\Entity\Congres\GeneralContribution
            - sonata.admin.congres.contribution_controller
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.congres.contribution_controller:
        class: AppBundle\Admin\Congres\Controller\ContributionAdminController
        calls:
            - [ setContainer, [@service_container] ]

    app.admin.event:
        class: AppBundle\Admin\EventAdmin
        arguments: [~, AppBundle\Entity\Event\Event, AppBundle:EventAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Evenements", label: "Évenements"}

    app.admin.event_role:
        class: AppBundle\Admin\EventRoleAdmin
        arguments: [~, AppBundle\Entity\Event\EventRole, SonataAdminBundle:CRUD]
        tags:

    app.admin.sleeping_facility:
        class: AppBundle\Admin\SleepingFacilityAdmin
        arguments: [~, AppBundle\Entity\Event\SleepingFacility, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Evenements", label: SleepingFacility}
