services:
    sonata.admin.adherent:
        class: AppBundle\Admin\AdherentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Fichier", label: "Adhérents"}
        arguments:
            - ~
            - AppBundle\Entity\Adherent
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.instance:
        class: AppBundle\Admin\ResponsabilityAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Fichier", label: "Responsabilités"}
        arguments:
            - ~
            - AppBundle\Entity\Responsability
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.user:
        class: AppBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Application", label: "Utilisateurs du site"}
        arguments:
            - ~
            - AppBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.acces:
        class: AppBundle\Admin\AccessAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Application", label: "Gestion des accès"}
        arguments:
            - ~
            - AppBundle\Entity\Access
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
            - [ setRouter, [@router] ]
    sonata.admin.congres.thematic_contribution:
        class: AppBundle\Admin\Congres\ThematicContributionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Congrès 2015", label: "Contributions thématiques"}
        arguments:
            - ~
            - AppBundle\Entity\Congres\ThematicContribution
            - sonata.admin.congres.contribution_controller
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.congres.general_contribution:
        class: AppBundle\Admin\Congres\GeneralContributionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Congrès 2015", label: "Contributions générales"}
        arguments:
            - ~
            - AppBundle\Entity\Congres\GeneralContribution
            - sonata.admin.congres.contribution_controller
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.congres.contribution_controller:
        class: AppBundle\Admin\Congres\Controller\ContributionAdminController
        calls:
            - [ setContainer, [@service_container] ]

    app.admin.event:
        class: AppBundle\Admin\EventAdmin
        arguments: [~, AppBundle\Entity\Event\Event, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Evenements", label: "Évenements"}

    app.admin.event_adherent_registration:
        class: AppBundle\Admin\EventAdherentRegistrationAdmin
        arguments: [~, AppBundle\Entity\Event\EventAdherentRegistration, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Evenements", label: "Inscription des adherents"}


    app.admin.sleeping_facility:
        class: AppBundle\Admin\SleepingFacilityAdmin
        arguments: [~, AppBundle\Entity\Event\SleepingFacility, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Evenements", label: "Lieu de couchage"}

    app.admin.address:
        class: AppBundle\Admin\AddressAdmin
        arguments: [~, AppBundle\Entity\Address, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Address, show_in_dashboard: false }

    app.admin.text_group:
        class: AppBundle\Admin\TextGroupAdmin
        arguments: [~, AppBundle\Entity\Text\TextGroup, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Texte", label: "Groupes de textes"}

    app.admin.text:
        class: AppBundle\Admin\TextAdmin
        arguments: [~, AppBundle\Entity\Text\Text, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Texte", label: "Textes"}

    app.admin.vote_rule:
        class: AppBundle\Admin\VoteRuleAdmin
        arguments: [~, AppBundle\Entity\Vote\VoteRule, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Texte", label: "Règles de votes", show_in_dashboard: false }
        calls:
            - [setSubClasses, [{threshold: AppBundle\Entity\Vote\ThresholdVoteRule}]]


    app.admin.event_meal:
        class: AppBundle\Admin\EventMealAdmin
        arguments: [~, AppBundle\Entity\Event\EventMeal, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: EventMeal, show_in_dashboard: false }

    app.admin.event_cost:
        class: AppBundle\Admin\EventCostAdmin
        arguments: [~, AppBundle\Entity\Event\EventCost, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: EventCost, show_in_dashboard: false }

    app.admin.event_role:
        class: AppBundle\Admin\EventRoleAdmin
        arguments: [~, AppBundle\Entity\Event\EventRole, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Evenements", label: "Rôles d'évenements", show_in_dashboard: false }
