services:
    sonata.admin.adherent:
        class: AppBundle\Admin\AdherentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Fichier", label: "Adhérents"}
        arguments:
            - ~
            - AppBundle\Entity\Adherent
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.user:
        class: AppBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Application", label: "Utilisateurs"}
        arguments:
            - ~
            - AppBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.congres.thematic_contribution:
        class: AppBundle\Admin\Congres\ThematicContributionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Congrès 2015", label: "Contributions thématiques"}
        arguments:
            - ~
            - AppBundle\Entity\Congres\ThematicContribution
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.congres.general_contribution:
        class: AppBundle\Admin\Congres\GeneralContributionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Congrès 2015", label: "Contributions générales"}
        arguments:
            - ~
            - AppBundle\Entity\Congres\GeneralContribution
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
