AppBundle\Entity\Congres\GeneralContribution:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: author
            message: "Tu ne peux poster qu'une seule contribution générale."
