<?php

namespace AppBundle\Entity\Congres;

use Doctrine\ORM\EntityRepository;

/**
 * ContributionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContributionsRepository extends EntityRepository
{
}
