<?php

namespace AppBundle\Entity\Congres;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\Criteria;
use AppBundle\Entity\Instance;
/**
 * GeneralContributionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeneralContributionRepository extends EntityRepository
{

    public function getCNVotesCount($contrib)
    {
        // TODO
        return 0;

    }

    public function getVotesCount($contrib)
    {
        // TODO
        return 0;
    }
    public function hasVoted($user)
    {
        $hasVoted = $this->createQueryBuilder('gc')
            ->select('COUNT(gc)')
            ->innerJoin('gc.votes', 'u')
            ->where('u.id = :user')
            ->setParameter('user', $user->getId())
            ->getQuery()->getSingleScalarResult();

        return $hasVoted;
    }

    public function hasAlreadyVoted($contrib, $user)
    {
        $hasAlreadyVoted = $this->createQueryBuilder('gc')
            ->select('COUNT(gc)')
            ->innerJoin('gc.votes', 'u')
            ->where('u.id = :user')
            ->andWhere('gc.id = :id')
            ->setParameter('user', $user->getId())
            ->setParameter('id', $contrib->getId())
            ->getQuery()->getSingleScalarResult();
        return $hasAlreadyVoted;
    }
}
