<?php

namespace AppBundle\Entity\Congres;

/**
 * GeneralContributionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeneralContributionRepository extends ContributionRepository
{
}
