<?php

namespace AppBundle\Entity\Congres;

use Doctrine\ORM\EntityRepository;

/**
 * PlatformContributionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatformContributionRepository extends EntityRepository
{
}
