<?php

namespace AppBundle\Entity\Congres;

/**
 * StatuteContributionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatuteContributionRepository extends ContributionRepository
{
    protected $classname = 'AppBundle\Entity\Congres\StatuteContribution';
}
