<?php

namespace AppBundle\Entity\Congres;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\Criteria;

/**
 * ThematicContributionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThematicContributionRepository extends EntityRepository
{
    public function getCNVotesCount()
    {
        // TODO
        return 0;
    }

    public function getVotesCount()
    {
        // TODO
        return 0;
    }
}
