<?php

namespace AppBundle\Entity\Congres;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\Criteria;

/**
 * ThematicContributionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThematicContributionRepository extends EntityRepository
{
    public function getCNVotesCount()
    {
        // TODO
        return 0;
    }

    public function getVotesCount()
    {
        // TODO
        return 0;
    }

    public function hasAlreadyVoted($contrib, $user)
    {
        $hasAlreadyVoted = $this->createQueryBuilder('tc')
            ->select('COUNT(tc)')
            ->innerJoin('tc.votes', 'u')
            ->where('u.id = :user')
            ->andWhere('tc.id = :id')
            ->setParameter('user', $user->getId())
            ->setParameter('id', $contrib->getId())
            ->getQuery()->getSingleScalarResult();

        var_dump($hasAlreadyVoted);
        return $hasAlreadyVoted;
    }
}
