<?php

namespace AppBundle\Entity\Congres;

use Doctrine\ORM\EntityRepository;

/**
 * ThematicContributionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThematicContributionsRepository extends EntityRepository
{
}
