<?php

namespace AppBundle\Entity\Congres;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping\ClassMetadata;
use AppBundle\Entity\Adherent;
use AppBundle\Entity\Text\TextGroup;

/**
 * ContributionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndividualTextVoteRepository extends EntityRepository
{
    protected $classname;

    public function getAdherentVoteCountByTextGroup(Adherent $author,TextGroup $textGroup)
    {
        $voteCount = $this->createQueryBuilder('itv')
            ->select('COUNT(itv)')
            ->where('itv.textGroup = :textGroup')
            ->andWhere('itv.author = :author')
            ->setParameter('author', $author->getId())
            ->setParameter('textGroup', $textGroup->getId())
            ->getQuery()->getSingleScalarResult();

        return $voteCount;
    }

}
