<?php

namespace AppBundle\Entity\Process;

/**
 * AmendmentProcessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmendmentProcessRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOpenedAtDate(\DateTime $date = null)
    {
        if (!isset($date)) {
            $date = new \DateTime('now');
        }
        return $this->createQueryBuilder('ap')
                ->where('ap.begin < :date')
                ->andWhere('ap.end > :date')
                ->setParameter(':date', $date)
            ->getQuery()
            ->getResult();
    }
}
