<?php

namespace AppBundle\Entity\Process;

/**
 * AmendmentTopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmendmentTopicRepository extends \Doctrine\ORM\EntityRepository
{
}
