<?php

namespace AppBundle\Entity\Process;

/**
 * AmendmentProcessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmendmentProcessRepository extends \Doctrine\ORM\EntityRepository
{
}
