<?php

namespace AppBundle\Entity\Process;

/**
 * ParticipationRuleTermRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationRuleTermRepository extends \Doctrine\ORM\EntityRepository
{
}
