<?php

namespace AppBundle\Entity\Process;

/**
 * ParticipationRuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationRuleRepository extends \Doctrine\ORM\EntityRepository
{
}
