<?php

namespace AppBundle\Entity\Event;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Adherent;

/**
 * EventRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRoleRepository  extends EntityRepository
{
    protected $classname = 'AppBundle\Entity\Event\EventRole';

    public function findByEventAndAdherentQueryBuider(Event $event, Adherent $adherent)
    {
        return $this->createQueryBuilder('er')
            ->leftJoin('er.requiredResponsabilities', 'reqresp')
            ->leftJoin('reqresp.adherentResponsabilities' , 'adhresp')
            ->where('er.event = :event')
            ->andWhere('adhresp.adherent = :adherent OR SIZE(er.requiredResponsabilities) = 0')
            ->setParameter('event', $event->getId())
            ->setParameter('adherent', $adherent->getId())
            ;
    }
}
