<?php

namespace AppBundle\Entity\Event;

/**
 * EventPriceScaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventPriceScaleRepository extends \Doctrine\ORM\EntityRepository
{
}
