<?php

namespace AppBundle\Entity\Event;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    protected $classname = 'AppBundle\Entity\Event\Event';

    public function findOpenedAtDate(\DateTime $date = null)
    {
        if (!isset($date)) {
            $date = new \DateTime('now');
        }
        return $this->createQueryBuilder('e')
                ->where('e.registrationBegin < :date')
                ->andWhere('e.registrationEnd > :date')
                ->setParameter(':date', $date)
            ->getQuery()
            ->getResult();
    }
}
