<?php

namespace AppBundle\Entity\Event;

/**
 * EventSleepingTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventSleepingTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
