<?php

namespace AppBundle\Entity\Event;

use Doctrine\ORM\EntityRepository;

/**
 * EventAdherentRegistrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventAdherentRegistrationRepository extends EntityRepository
{
    protected $classname = 'AppBundle\Entity\Event\EventAdherentRegistration';


}
