<?php

namespace AppBundle\Entity\Event;

use Doctrine\ORM\EntityRepository;

/**
 * EventCostRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventCostRepository extends EntityRepository
{
    protected $classname = 'AppBundle\Entity\Event\EventCost';

    public function findByEventQueryBuider(Event $event)
    {
        return $this->createQueryBuilder('ec')
            ->where('ec.event = :event')
            ->setParameter('event', $event->getId())
            ;
    }
}
