<?php

namespace AppBundle\Entity\Event;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Payment\Payment;

/**
 * EventAdherentRegistrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventAdherentRegistrationRepository extends EntityRepository
{
    protected $classname = 'AppBundle\Entity\Event\EventAdherentRegistration';

    public function getPayedAmountById(EventAdherentRegistration $ear)
    {
        $payedAmount = $this->createQueryBuilder('ear')
            ->select('SUM(p.amount)')
            ->innerJoin('ear.payments', 'p')
            ->where('ear.id = :ear')
            ->andWhere('p.status = :status')
            ->setParameter('ear', $ear->getId())
            ->setParameter('status', Payment::STATUS_BANKED)
            ->getQuery()->getSingleScalarResult();

        return $payedAmount;
    }

}
